# Functions and Libraries 
<!-- a.m. class -->

## Functions 
functions are reusable blocks of code that perform a specific task, assisting the resolution of complex problems into simpler parts. Creating function makes the code more modular, readable and maintainable. We *create* a function with `def():` and *call* it by just enuncing it's name. Is a good practice to specify the *return* we expect, many functions will need this specification to be able to work.

As in many other languages, a variable defined inside a function are local to that function. Variables defined outside the function can be called but not modified inside the function. 

In [2]:
#define a function called greet
def greet(name): 
    print(f"Hello {name}") 

greet("Alice")

Hello Alice


In [4]:
employee="Maria"

#call the function with a previusly defined variable
greet(employee)

Hello Maria


In [6]:
#define a function called greet but with a slight modification
def greet(name): 
    name=name.upper()
    print(f"Hello {name}") 

greet("Alice")
greet(employee)

Hello ALICE
Hello MARIA


As we are in a jupyter notebook the variable employee remains unchanged after aplying the function. But in a purely *python* environment if we call employee after running the function on it we should get MARIA. 

In [18]:
#Exercise
def calculate_area(x,y):
    a = x*y 
    return a 

def introduction(name, age=25): 
    print(f"I'm {name}, I'm {age} years old.")

def first_last(element): 
    f = element[0]
    l = element[-1]
    return f,l

print(calculate_area(2,2))
introduction("Maria",29) 
print(first_last([1,2,3,3,4,5,6,7,8,"a"]))

4
I'm Maria, I'm 29 years old.
(1, 'a')


## Modules and libraries
Modules are files that contain a set of functions, in consquence, a library is a collection of modules that offer a wide range of functionalities.
**Libraries** are efficient functional have a supporting community.

Common libraries are *Math, Sys, Os* and *Datetime* which are predefined on python. 

Libraries must be installed and imported. Once imported, we use de module name with a dot to access its functions `module_name.function_name()`. We can also import a module or a function. 

**NOTE: we usually install and import all of our libraries at the begining of our code**

In [31]:
#import
import numpy

#call a function
numpy.arange(100, 200, 33)

array([100, 133, 166, 199])

In [33]:
# to import a specific function
from numpy import arange

#now we are able to call just the function withouth enuncing the library/module
arange(100, 200, 33)

array([100, 133, 166, 199])

In [36]:
#import the math library
import math

#try the function to compuite the square root
math.sqrt(16)

4.0

In [42]:
# Datetime library 
import datetime as dt 

#see the result from the function 
print(dt.datetime.now()) # in this case we have library.class.function (see always documentation)

#as it not very readable we define as a variable
now = dt.datetime.now()
now.strftime("%d/%m/%Y %H:%M") #we apply a string format 

2026-02-18 09:59:32.725854


'18/02/2026 09:59'

In [56]:
# Exercise 2
# import only the randint function and generate a ranfom integer between 1 to 10
from random import randint
print(randint(1,10))

# install and use requests
#!pip install requests

import requests
url = "https://www.stats.govt.nz/assets/Uploads/Business-operations-survey/Business-operations-survey-2022/Download-data/business-operations-survey-2022-business-finance.csv"
response = requests.get(url)

#check the first 50 characters of the content
response.text[:50]


6


'description,industry,level,size,line_code,value\r\nT'

In [58]:
### OS library 
import os 
os.getcwd()

'C:\\Users\\marub\\Documents\\GitHub\\icatt_dsm_python'

## CSV library
Python's csv module allows us to interact with CSV files with ease. The module supports various functions to read from and write to CSV files

**TIPS: Always close the files using a context manager (with statement) to ensure proper resource management.**

In [60]:
import csv

#define path (usually we use this with the open function
file_path=os.getcwd()

#open the file
with open("my_data.csv") as f: 
    reader = csv.reader (f)

    for row in reader:
        print(row)

['id', 'name', 'age', 'city']
['1', 'maria', '29', 'Santiago']
['2', 'alice', '34', 'New York']
['3', 'camila', '30', 'Buenos Aires']
['4', 'Fernando', '25', 'Madrid']
['5', 'Dalas', '36', 'Dalas']


## Tkinter
Is the standard Python interface to the Tk GUI toolkit. It's built in python readily available for quick prototyping. 

In [ ]:
import tkinter as tk

#create a desktop app
root = tk.Tk()

#start adding the elements
root.title("Mi first Tkinker Window") #title
label = tk.Label(root, text="Hello There...") #label for the Window
label.pack()

#what we will do with the button
def on_button_click():
    label.config(text="General Kenobi!") #change the window's label

#now we actually create the button 
button=tk.Button(root, text="Only-right-answer button", command=on_button_click)
button.pack()

#run the app
root.mainloop()

## NumPy
Is a fundamental package for scientific computing, provides datsa structures implementin multi-dimensional arrays and matrices, used for efficient computations on large volumes of data. 

A **NumPy array** is a grid of values, all of the same type, indexed by a tuple of non-negative integers. They are more compact, faster and functional than a python list. These arrays enable vectorized operations, that in turn lead to cleaner code and better performance. Examples include *element-wise arithmetic, logical, and functional operations*.

In [65]:
# import 
import numpy as np

#create and see an array
my_array = np.array([1,10,-5,20])
print(my_array)

#now we want to se the mean 
print(f"The mean is {my_array.mean()}")
#or the sd
print(f"The mean is {my_array.std()}")

#what if we want to multiply the array by 2 
print(f"Multiplication by 2: {my_array*2}")

[ 1 10 -5 20]
The mean is 6.5
The mean is 9.447221813845593
Multiplication by 2: [  2  20 -10  40]


We can also find muti-domensional arrays and manipulate them

In [74]:
#multi-dimensional array 4x3
my_mdarray = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(my_mdarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [75]:
#we can multiply 
print(f"Multiplication by 2: \n { my_mdarray*4}")

Multiplication by 2: 
 [[ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]


In [76]:
#we can Transpose
print(f"Transposed matrix: \n { my_mdarray.T}")

Transposed matrix: 
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [77]:
#we can find the size or the shape of the matrix 
print(f"size: {my_mdarray.size}; shape: {my_mdarray.shape}")

size: 12; shape: (4, 3)


In [80]:
# Excersise 3 

# to generate 20 random numbers from 100 to 200
rd20 = np.random.randint(100,200,20)
print(rd20)

#create a new list of numbers with just the evens
even_rd20 = rd20[rd20 % 2 == 0]
print(even_rd20)

[162 131 140 151 192 129 112 133 194 136 117 111 172 174 189 106 114 192
 156 154]
[162 140 192 112 194 136 172 174 106 114 192 156 154]


In [82]:
#we want the even numbers but from the position 2 to 8. 
sliced_even_rd20 = even_rd20[2:8]
print(sliced_even_rd20)

[192 112 194 136 172 174]


In [84]:
#example
arr1=np.random.randint(0,7,4)
arr2=np.random.randint(0,7,4)

#multiplication 
print(arr1*arr2)
print(np.dot(arr1, arr2))

[10  0 20  0]
30
