# Tkinker

In [13]:
import tkinter as tk

#create a desktop app
root = tk.Tk()

#start adding the elements
root.title("Mi first Tkinker Window") #title
label = tk.Label(root, text="Hello There...") #label for the Window
label.pack()

#what we will do with the button
def on_button_click():
    label.config(text="General Kenobi!") #change the window's label

#now we actually create the button 
button=tk.Button(root, text="Only-right-answer button", command=on_button_click)
button.pack()

#run the app
root.mainloop()

# NumPy 

In [15]:
import numpy as np

# to generate 20 random numbers from 100 to 200
rd20 = np.random.randint(100,200,20)
print(rd20)

#create a new list of numbers with just the evens
even_rd20 = rd20[rd20 % 2 == 0]
print(even_rd20)

sliced_even_rd20 = even_rd20[2:8]
print(sliced_even_rd20)

[137 176 109 181 190 168 108 121 101 149 100 129 195 109 161 154 129 181
 153 172]
[176 190 168 108 100 154 172]
[168 108 100 154 172]


## Excercise 4

After generate a csv with random numbers in excel:

In [26]:
#open the file with np
randomdata = np.genfromtxt("../data/randomdata.csv", delimiter=";")
randomdata

array([[148., 103., 156., ..., 123., 106., 146.],
       [188., 174., 195., ..., 197., 159., 143.],
       [199., 133., 106., ..., 105., 162., 191.],
       ...,
       [134., 172., 124., ..., 116., 122., 117.],
       [126., 112., 144., ..., 103., 156., 162.],
       [195., 183., 192., ..., 107., 189., 180.]], shape=(49, 27))

In [28]:
randomdata.sum()

np.float64(197780.0)

In [31]:
#retrieve one specific column from the dataset
column_index = 0 
column_data=randomdata[:, column_index]
column_data

array([148., 188., 199., 129., 109., 166., 142., 161., 193., 140., 196.,
       197., 133., 148., 122., 195., 167., 157., 169., 128., 192., 176.,
       138., 164., 136., 198., 128., 133., 150., 117., 190., 163., 102.,
       166., 130., 196., 140., 133., 175., 151., 155., 106., 154., 171.,
       155., 115., 134., 126., 195.])

# Matplotlib
